[WIP]データベースReadME作成
hitourebito/chat-space pull request #1
Opened 2019-05-18 06:45 UTC by hitourebito

#WHAT
データベース作成に必要なテーブル情報をまとめる

#WHY
サービス制作および運営を円滑に進めるため

2019-05-18 06:49 UTC, miyagit reviewed
全体的にテーブル設計がうまくいっていないのでメンターに質問してチャットスペースのテーブル設計について理解しましょう。

2019-05-18 06:51 UTC, hitourebito commented
わかりました。メンターに質問してみます。

2019-05-18 07:11 UTC, hitourebito commented
メンターに質問し、アソシエーションの部分について修正しました。

2019-05-18 07:19 UTC, i-date commented on README.md
> +|member_id|integer|null: false, foreign_key: true|
groupsテーブルはmembersテーブルに所属しているわけではないので7行目は必要ありません。

2019-05-18 07:19 UTC, i-date commented on README.md
> +- has_many :members
messagesテーブルとのアソシエーションも追加しましょう。

2019-05-18 07:19 UTC, i-date commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
Railsでは外部キーは integer 型ではなく、references 型を使用しましょう。
また、そうすることで `user_id` を `user` と記述するとテーブルが生成される時に _id が付与されます。
あと他の外部キーも修正しましょう。

2019-05-18 07:19 UTC, i-date commented on README.md
> +- has_many :members
messagesテーブルとのアソシエーションも追加しましょう。

2019-05-18 07:19 UTC, i-date commented on README.md
> +|body|string|null: false|
string型ではなく、text型にしましょう。
また、imageカラム（string型）を追加して、メッセージと画像どちらか片方で投稿できるようにしましょう。

2019-05-18 07:19 UTC, i-date commented on README.md
> +|member_id|integer|null: false, foreign_key: true|
membersテーブルではなく、usersテーブルとgroupsテーブルの外部キーにしましょう。
そのため、アソシエーションも見直しましょう。

2019-05-19 04:48 UTC, hitourebito commented on README.md
> +|member_id|integer|null: false, foreign_key: true|
修正しました。

2019-05-19 04:49 UTC, hitourebito commented on README.md
> +- has_many :members
追加しました

2019-05-19 04:55 UTC, hitourebito commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
外部キーに関する記述修正しました

2019-05-19 04:57 UTC, hitourebito commented on README.md
> +- has_many :members
アソシエーション追加しました

2019-05-19 05:09 UTC, hitourebito commented on README.md
> +|body|string|null: false|
imageカラムを追加しました。メッセージと画像どちらか片方で投稿できるようにするにはnull以下の記述を変更すればできるかと思うのですが、カリキュラムに乗ってますでしょうか？

2019-05-19 05:14 UTC, hitourebito commented on README.md
> +|member_id|integer|null: false, foreign_key: true|
外部キーへと記述修正、およびアソシエーション修正しました。

2019-05-19 05:35 UTC, ghost requested changes

2019-05-19 05:35 UTC, hiroki5123 commented on README.md
> +|body|text|null: false|
画像だけで送れるようにしたいのでNOT NULL外しましょう

2019-05-19 05:35 UTC, hiroki5123 commented on README.md
> +|image|string|null: false|
こちらも

2019-05-19 05:40 UTC, hitourebito commented on README.md
> +|body|text|null: false|
NOT NULL外しました。

2019-05-19 05:41 UTC, hitourebito commented on README.md
> +|image|string|null: false|
NOT NULL外しました

2019-05-19 06:14 UTC, kuroko918 commented on README.md
>  This README would normally document whatever steps are necessary to get the
この行以下の不要な記述は消しておきましょう！

2019-05-19 06:40 UTC, hitourebito commented on README.md
>  This README would normally document whatever steps are necessary to get the
49行目以下不要な部分削除しました。

2019-05-19 06:44 UTC, ghost approved these changes
LGTMです！

2019-05-19 06:46 UTC, merged